# Dedicated CI/CD service account
serviceAccount: projects/cicd-demo-project-481705/serviceAccounts/service-account-cicd-pipline@cicd-demo-project-481705.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1️⃣ Build Docker Image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - "-t"
    - "asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-test-repo/app:$BUILD_ID"
    - "."

# 2️⃣ Push Image to Artifact Registry
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - "asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-test-repo/app:$BUILD_ID"

# 3️⃣ Deploy to DEV GKE
- name: gcr.io/cloud-builders/kubectl
  entrypoint: bash
  args:
    - -c
    - |
      gcloud container clusters get-credentials dev-cluster --zone asia-south1-a
      kubectl set image deployment/app app=asia-south1-docker.pkg.dev/$PROJECT_ID/my-test-docker-repo/app:$BUILD_ID
      kubectl rollout status deployment/app

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-test-repo/app:$BUILD_ID
