apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: asia-south1-docker.pkg.dev/cicd-demo-project-481705/my-docker-test-repo/app:latest
        ports:
        - containerPort: 8080
